first quest
AtremBi/java-explore-with-me pull request #3
Opened 2023-10-15 20:23 UTC by AtremBi

2023-10-16 08:30 UTC, tomattman requested changes
Привет, работа хорошая, есть пара комментариев, но основной момент что надо переделать это мусор в структуре приложения

2023-10-16 08:30 UTC, tomattman commented on stats/stats-client/src/main/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
какая то каша со структурой проекта, почему пом файл находится в этой папке?

2023-10-16 08:30 UTC, tomattman commented on stats/stats-dto/src/main/java/ru/practicum/explore_with_me/dto/StatsDtoForSave.java
> +public class StatsDtoForSave {
часто такие классы называют относительно того где они будут использоваться
например StatsRequestDto или StatsResponseDto

2023-10-16 08:30 UTC, tomattman commented on stats/stats-dto/src/main/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Снова файл где то не там

2023-10-16 08:30 UTC, tomattman commented on stats/stats-service/src/main/java/ru/practicum/explore_with_me/model/Stat.java
> +    private Application app;
хороший варинат с связанной таблицей для приложений

2023-10-16 08:30 UTC, tomattman commented on stats/stats-service/src/main/java/ru/practicum/explore_with_me/repository/ApplicationRepository.java
> +    Optional<Application> findByApp(String appName);
ты уверен что данный запрос будет работать правильно?
Поиск по app у которого в id число, а передается в параметрах строка

2023-10-16 08:30 UTC, tomattman commented on stats/stats-client/src/main/java/ru/practicum/explore_with_me/StatsClient.java
> +        for (int i = 0; i < uris.length; i++) {
вариант попроще, у стримов есть коллекторы которые объединяют строки с разделителем, и они сами все это делают

2023-10-16 08:30 UTC, tomattman commented on docker-compose.yml
> +      - "6542:5432"
странный маппинг портов, разве постгрес по умолчанию не использует порт 5432

2023-10-17 19:42 UTC, AtremBi commented on stats/stats-service/src/main/java/ru/practicum/explore_with_me/repository/ApplicationRepository.java
> +    Optional<Application> findByApp(String appName);
так это же поиск по имени
![image](https://github.com/AtremBi/java-explore-with-me/assets/93490879/fc247612-c879-43cd-9d56-34fab7cc4bf2)

2023-10-18 07:38 UTC, tomattman approved these changes
Принято

2023-10-23 22:58 UTC, merged